parameters:
    unrestricted_select_attribute_catalog.updater.setter.create_option_value.class : Niji\AutoAttributeOptionsSetterBundle\Component\Catalog\Updater\Setter\UnrestrictedCreateOptionValue
    unrestricted_select_attribute_catalog.updater.setter.multiselect_value.class : Niji\AutoAttributeOptionsSetterBundle\Component\Catalog\Updater\Setter\UnrestrictedMultiSelectAttributeSetter
    unrestricted_select_attribute_catalog.updater.setter.simpleselect_value.class : Niji\AutoAttributeOptionsSetterBundle\Component\Catalog\Updater\Setter\UnrestrictedSimpleSelectAttributeSetter

services:

    pim_catalog.updater.setter.multiselect_value:
        class: '%unrestricted_select_attribute_catalog.updater.setter.multiselect_value.class%'
        parent: pim_catalog.updater.setter.abstract
        arguments:
            - ['pim_catalog_multiselect']
            - '@pim_catalog.repository.attribute_option'
            - '@unrestricted_select_attribute_catalog.updater.setter.create_option_value'
        tags:
            - { name: 'pim_catalog.updater.setter' }

    pim_catalog.updater.setter.simpleselect_value:
        class: '%unrestricted_select_attribute_catalog.updater.setter.simpleselect_value.class%'
        parent: pim_catalog.updater.setter.abstract
        arguments:
            - ['pim_catalog_simpleselect']
            - '@pim_catalog.repository.attribute_option'
            - '@unrestricted_select_attribute_catalog.updater.setter.create_option_value'
        tags:
            - { name: 'pim_catalog.updater.setter' }

    unrestricted_select_attribute_catalog.updater.setter.create_option_value:
        class: '%unrestricted_select_attribute_catalog.updater.setter.create_option_value.class%'
        arguments:
            - '@pim_catalog.factory.attribute_option'
            - '@pim_catalog.updater.attribute_option'
            - '@pim_catalog.saver.attribute_option'
            - '@akeneo_storage_utils.doctrine.object_detacher'